
wallpaper {
    monitor = DP-1
    path = /home/kreten/Pictures/wallpapers/wall_cyberpunk.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/kreten/Pictures/wallpapers/wall_porshe.jpg
    fit_mode = cover
  }
